auto: true

#markdown: rdiscount
highlighter: 'pygments'
#paginate: 8
permalink: /:title

title: Hyper Hamster
url: http://yangwu200799.github.io
feed: /atom.xml
author_info: <a href="http://yangwu200799.github.io/">YangWu</a>
